name: prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: '# known hosts'
      - name: add known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: start or reload
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} '
            cd ${{ secrets.PATH_HOME }}
            pm2 startOrReload ecosystem.config.js -s --only cabral.ro
          '
